# Generated by Django 3.2.9 on 2023-02-26 12:41

import banking_app.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=banking_app.services.generate_account_number, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
